SPEXAPC-2212 adressing PR comments

diff --git a/charts/quay-obj-backup/templates/backup-scripts-cm.yaml b/charts/quay-obj-backup/templates/backup-scripts-cm.yaml
--- a/charts/quay-obj-backup/templates/backup-scripts-cm.yaml
+++ b/charts/quay-obj-backup/templates/backup-scripts-cm.yaml
@@ -12,6 +12,7 @@ data:
   env.retention: {{ .Values.retentionDays | quote }}
   quayObjBackup.sh: |
     #!/bin/bash
+    set -u
 
     log_message() {
       local timestamp
@@ -60,6 +61,7 @@ data:
 
   s3upload.sh: |
     #!/bin/bash
+    set -u
 
     log_message() {
       local timestamp
@@ -73,10 +75,10 @@ data:
       done < $1
     }
 
-    # check snapshot file
-    SNAPSHOT_FILE=$(find /backup -type f -mmin -30 -name "${FILEPREFIX}*" | sort | tail -1)
-    if ! test -r "$SNAPSHOT_FILE"; then
-      log_message "ERROR: Failed to locate a valid snapshot file."
+    # check backup file
+    BACKUP_FILE=$(find /backup -type f -mmin -30 -name "${FILEPREFIX}*" | sort | tail -1)
+    if ! test -r "$BACKUP_FILE"; then
+      log_message "ERROR: Failed to locate a valid backup file."
       exit 1
     fi
 
@@ -86,19 +88,19 @@ data:
     export AWS_ENDPOINT_URL="https://${BUCKET_HOST}:${BUCKET_PORT}"
 
     # upload backup to s3 bucket
-    if ! aws s3 cp "$SNAPSHOT_FILE" "s3://$BUCKET_NAME" --no-progress 2>/dev/shm/out.err 1>/dev/null; then
+    if ! aws s3 cp "$BACKUP_FILE" "s3://$BUCKET_NAME" --no-progress 2>/dev/shm/out.err 1>/dev/null; then
       log_messagef /dev/shm/out.err
-      log_message "ERROR: Failed to upload $(basename "$SNAPSHOT_FILE") to s3://$BUCKET_NAME "
+      log_message "ERROR: Failed to upload $(basename "$BACKUP_FILE") to s3://$BUCKET_NAME "
       exit 2
     fi
 
-    if ! aws s3api head-object --bucket "$BUCKET_NAME" --key $(basename "$SNAPSHOT_FILE") 2>/dev/shm/out.err 1>/dev/null; then
+    if ! aws s3api head-object --bucket "$BUCKET_NAME" --key $(basename "$BACKUP_FILE") 2>/dev/shm/out.err 1>/dev/null; then
       log_messagef /dev/shm/out.err
-      log_message "ERROR: Unable to verify uploaded object s3://${BUCKET_NAME}/$(basename "$SNAPSHOT_FILE")"
+      log_message "ERROR: Unable to verify uploaded object s3://${BUCKET_NAME}/$(basename "$BACKUP_FILE")"
       exit 2
     fi
 
-    log_message "Snapshot has been uploaded to s3://${BUCKET_NAME}/$(basename "$SNAPSHOT_FILE")"
+    log_message "backup has been uploaded to s3://${BUCKET_NAME}/$(basename "$BACKUP_FILE")"
 
     # run cleanup
     if ! expr "$RETENTION" : '^[0-9]\+$' 2>/dev/shm/out.err 1>/dev/null; then
